version: "3.8"

services:
  fsb:
      build: .
      restart: unless-stopped
      container_name: fsb
      environment:
      # required
       - API_ID=2201304 # change this to your ID
       - API_HASH=4862ee2bf0fe8fbad582cb26d3d12e77 # change this to your HASH
       - BOT_TOKEN=5411884013:AAG0nUmVlb5qDsP3UBHI7CyrcJ9iFB_Js3M #HHTGFilezDLBot
       - BIN_CHANNEL=-1001886225227 # paste channel ID
       - BIN_CHANNEL_WITHOUT_MINUS=1001886225227
      ports:
       - 127.0.0.1:8000:80
      volumes:
       - $HOME/TG-FSBot:/app/.env
